# Generated by Django 4.2.4 on 2023-08-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listanime',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
