# Generated by Django 4.2.4 on 2023-08-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_listanime_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
