# Generated by Django 4.2.4 on 2023-08-12 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_alter_anime_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
